### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by CrashLaker** [CrashLaker/grafana-horizon#12]
* Viz Engines
   * [x] Regular
   * [x] Horizon
   * [x] Discrete
   * [x] BarPlot
   * [x] DotPlot
* Fix bugs:
    * [ ] Label values missing when interval is larger then threshold #19
    * [ ] Fix context draw is propagating in discrete vis when there's no data #4
    * [x] Mouse value seek from position #10
    * [x] Fill graph when box width is larger than 1pixel intervals #11
    * [x] Wide format... #7
    * [x] Barplot vis ignore negative scales when there are only negative or positive numbers #2
* Styles:
    * [x] Sketchy vis
*  Show:
    * [x] Labels
    * [x] Ruler Values
    * [x] Mirror/Offset View
* Set:
    * [x] bgColor
    * [x] Series Height
    * [x] Series Margin
    * [x] Bar Width
    * [x] Bar Margin Offset
    * [x] Thresholds
* Data:
    * [x] Sorting: [avg, percentile, max, min, last]
    * [x] Sort order
* Extra
    * [x] DummyData
    * [x] Anonymize
* Enhancement
    * [ ] emit and receive crosshair events #17
